[package]
name = "semblance-wast"
version = "0.1.0"
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
semblance = { path = "../semblance" }
wast = { version = "243.0.0", features = ["wasm-module"] }
