[workspace]
members = ["crates/*"]
default-members = ["crates/semblance"]
resolver = "3"

[workspace.package]
homepage = "https://github.com/irrio/semblance"
repository = "https://github.com/irrio/semblance"
authors = ["Taylor Hogge <taylor@irreducible.io>"]
edition = "2024"
