[package]
name = "semblance-mars"
version = "0.1.0"
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
semblance = { path = "../semblance" }
sdl2 = { version = "0.38.0", features = ["unsafe_textures"] }
